//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chronos.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chronos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anwender hat den Vorgang abgebrochen ähnelt.
        /// </summary>
        public static string AbortAction {
            get {
                return ResourceManager.GetString("AbortAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über / Hilfe ähnelt.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinzufügen ähnelt.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieser Tag existiert bereits in der Datenbank. Bitte den Dialog schließen und BEARBEITEN wählen! ähnelt.
        /// </summary>
        public static string AddStatsAlreadyExist {
            get {
                return ResourceManager.GetString("AddStatsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tage dürfen nicht leer sein !!! ähnelt.
        /// </summary>
        public static string AddStatsDaysNotEmpty {
            get {
                return ResourceManager.GetString("AddStatsDaysNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start- und End-Tag müssen übereinstimmen !!! ähnelt.
        /// </summary>
        public static string AddStatsStartEndMustMatch {
            get {
                return ResourceManager.GetString("AddStatsStartEndMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anwendung ähnelt.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anwendung minimieren, statt zu beenden ähnelt.
        /// </summary>
        public static string ApplicationMinimize {
            get {
                return ResourceManager.GetString("ApplicationMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anwendung beenden, statt zu minimieren ähnelt.
        /// </summary>
        public static string ApplicationQuit {
            get {
                return ResourceManager.GetString("ApplicationQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatischer Start ähnelt.
        /// </summary>
        public static string Autostart {
            get {
                return ResourceManager.GetString("Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diagramm ähnelt.
        /// </summary>
        public static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenpunkte konnten nicht zum Diagramm hinzugefügt werden ähnelt.
        /// </summary>
        public static string ChartDatapointsFail {
            get {
                return ResourceManager.GetString("ChartDatapointsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diagramm erstellen ähnelt.
        /// </summary>
        public static string ChartGen {
            get {
                return ResourceManager.GetString("ChartGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chronos ähnelt.
        /// </summary>
        public static string Chronos {
            get {
                return ResourceManager.GetString("Chronos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chronos Arbeitszeiterfassung ähnelt.
        /// </summary>
        public static string ChronosDesc {
            get {
                return ResourceManager.GetString("ChronosDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In die Zwischenablage kopieren ähnelt.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erkanntes Land ähnelt.
        /// </summary>
        public static string CountryDetected {
            get {
                return ResourceManager.GetString("CountryDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konnte Land nicht erkennen. Verwende Fallback ähnelt.
        /// </summary>
        public static string CountryDetectFail {
            get {
                return ResourceManager.GetString("CountryDetectFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tägliche Arbeitszeit (Stunden) ähnelt.
        /// </summary>
        public static string DailyWorktime {
            get {
                return ResourceManager.GetString("DailyWorktime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum ähnelt.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tag ähnelt.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tag konnte nicht gelöscht werden ähnelt.
        /// </summary>
        public static string DayDeleteFail {
            get {
                return ResourceManager.GetString("DayDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tag wurde erfolgreich gelöscht ähnelt.
        /// </summary>
        public static string DayDeleteSuccess {
            get {
                return ResourceManager.GetString("DayDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tag konnte nicht bearbeitet werden ähnelt.
        /// </summary>
        public static string DayEditFail {
            get {
                return ResourceManager.GetString("DayEditFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tag wurde erfolgreich bearbeitet ähnelt.
        /// </summary>
        public static string DayEditSuccess {
            get {
                return ResourceManager.GetString("DayEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tag konnte nicht eingetragen werden ähnelt.
        /// </summary>
        public static string DayInsertFail {
            get {
                return ResourceManager.GetString("DayInsertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tag wurde erfolgreich eingetragen ähnelt.
        /// </summary>
        public static string DayInsertSuccess {
            get {
                return ResourceManager.GetString("DayInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deaktiviere  Feierabend-Erinnerung ähnelt.
        /// </summary>
        public static string DisableGoHomeReminder {
            get {
                return ResourceManager.GetString("DisableGoHomeReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verberge Fenster nicht beim Start ähnelt.
        /// </summary>
        public static string DontHideWindowOnStart {
            get {
                return ResourceManager.GetString("DontHideWindowOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starte nicht mit Windows ähnelt.
        /// </summary>
        public static string DontStartWithWindows {
            get {
                return ResourceManager.GetString("DontStartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktiviere Feierabend-Erinnerung ähnelt.
        /// </summary>
        public static string EnableGoHomeReminder {
            get {
                return ResourceManager.GetString("EnableGoHomeReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feierabend ähnelt.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportiere Arbeitszeit ähnelt.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner wählen ähnelt.
        /// </summary>
        public static string ExportCustomFolder {
            get {
                return ResourceManager.GetString("ExportCustomFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportiere in einen eigenen Ordner ähnelt.
        /// </summary>
        public static string ExportDefaultPathOff {
            get {
                return ResourceManager.GetString("ExportDefaultPathOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportiere in den Dokumente-Ordner ähnelt.
        /// </summary>
        public static string ExportDefaultPathOn {
            get {
                return ResourceManager.GetString("ExportDefaultPathOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export fehlgeschlagen ähnelt.
        /// </summary>
        public static string ExportFail {
            get {
                return ResourceManager.GetString("ExportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standard ist der Dokumente-Ordner des Anwenders ähnelt.
        /// </summary>
        public static string ExportFolderWatermark {
            get {
                return ResourceManager.GetString("ExportFolderWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monat exportieren ähnelt.
        /// </summary>
        public static string ExportMonth {
            get {
                return ResourceManager.GetString("ExportMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arbeitsrechtrelevanz ähnelt.
        /// </summary>
        public static string ExportRelevance {
            get {
                return ResourceManager.GetString("ExportRelevance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arbeitszeitexport ähnelt.
        /// </summary>
        public static string ExportSetting {
            get {
                return ResourceManager.GetString("ExportSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export erfolgreich ähnelt.
        /// </summary>
        public static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nur über 10 Stunden ähnelt.
        /// </summary>
        public static string ExportTenOff {
            get {
                return ResourceManager.GetString("ExportTenOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Tage ähnelt.
        /// </summary>
        public static string ExportTenOn {
            get {
                return ResourceManager.GetString("ExportTenOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Woche exportieren ähnelt.
        /// </summary>
        public static string ExportWeek {
            get {
                return ResourceManager.GetString("ExportWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jahr exportieren ähnelt.
        /// </summary>
        public static string ExportYear {
            get {
                return ResourceManager.GetString("ExportYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HEY! GEH NACH HAUSE ähnelt.
        /// </summary>
        public static string GoHomeNotifierCrit {
            get {
                return ResourceManager.GetString("GoHomeNotifierCrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wird Zeit nach Hause zu gehen ähnelt.
        /// </summary>
        public static string GoHomeNotifierWarn {
            get {
                return ResourceManager.GetString("GoHomeNotifierWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brutto ähnelt.
        /// </summary>
        public static string Gross {
            get {
                return ResourceManager.GetString("Gross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verberge Fenster beim Start ähnelt.
        /// </summary>
        public static string HideWindowOnStart {
            get {
                return ResourceManager.GetString("HideWindowOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feiertag ähnelt.
        /// </summary>
        public static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Berechne kommende, gesetzliche Feiertage. ähnelt.
        /// </summary>
        public static string HolidayCalculating {
            get {
                return ResourceManager.GetString("HolidayCalculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feiertage ähnelt.
        /// </summary>
        public static string Holidays {
            get {
                return ResourceManager.GetString("Holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konnte Job-Planer nicht initialisieren. Funktionalität eingeschränkt. ähnelt.
        /// </summary>
        public static string JobInitFailed {
            get {
                return ResourceManager.GetString("JobInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initialisiere Chronos Job Planer und stelle Intervall auf Minuten ähnelt.
        /// </summary>
        public static string JobInitMinutes {
            get {
                return ResourceManager.GetString("JobInitMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ebene ähnelt.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Protokoll ähnelt.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximale Arbeitszeit pro Tag (Stunden) ähnelt.
        /// </summary>
        public static string MaxDailyWorktime {
            get {
                return ResourceManager.GetString("MaxDailyWorktime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Meldung ähnelt.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fenster wurde zum Benachrichtigungssymbol minimiert. ähnelt.
        /// </summary>
        public static string MinToTray {
            get {
                return ResourceManager.GetString("MinToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Letzter Monat ähnelt.
        /// </summary>
        public static string MonthLast {
            get {
                return ResourceManager.GetString("MonthLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieser Monat ähnelt.
        /// </summary>
        public static string MonthThis {
            get {
                return ResourceManager.GetString("MonthThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Netto ähnelt.
        /// </summary>
        public static string Net {
            get {
                return ResourceManager.GetString("Net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benachrichtigungen ähnelt.
        /// </summary>
        public static string NotificationSetting {
            get {
                return ResourceManager.GetString("NotificationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exportverzeichnis öffnen ähnelt.
        /// </summary>
        public static string OpenExportFolder {
            get {
                return ResourceManager.GetString("OpenExportFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Portabel ähnelt.
        /// </summary>
        public static string Portable {
            get {
                return ResourceManager.GetString("Portable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Umstellung auf portablen Modus fehlgeschlagen ähnelt.
        /// </summary>
        public static string PortableFail {
            get {
                return ResourceManager.GetString("PortableFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade in portablem Modus ähnelt.
        /// </summary>
        public static string PortableMode {
            get {
                return ResourceManager.GetString("PortableMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade in Benutzerprofil-Modus ähnelt.
        /// </summary>
        public static string PortableModeOff {
            get {
                return ResourceManager.GetString("PortableModeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Umstellung auf portablen Modus erfolgreich ähnelt.
        /// </summary>
        public static string PortableSuccess {
            get {
                return ResourceManager.GetString("PortableSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Umstellung auf Profil-Modus fehlgeschlagen ähnelt.
        /// </summary>
        public static string PortableUndoFail {
            get {
                return ResourceManager.GetString("PortableUndoFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Umstellung auf Profil-Modus erfolgreich ähnelt.
        /// </summary>
        public static string PortableUndoSuccess {
            get {
                return ResourceManager.GetString("PortableUndoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drucken ähnelt.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anwendung beenden ähnelt.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konnte readme.xps Datei nicht lesen ähnelt.
        /// </summary>
        public static string ReadReadmeFail {
            get {
                return ResourceManager.GetString("ReadReadmeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anwendung konnte nicht zum Autostart hinzugefügt werden ähnelt.
        /// </summary>
        public static string RegisterFail {
            get {
                return ResourceManager.GetString("RegisterFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anwendung wird zum Autostart hinzugefügt ähnelt.
        /// </summary>
        public static string RegisterInfo {
            get {
                return ResourceManager.GetString("RegisterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anwendung wird vom Autostart entfernt ähnelt.
        /// </summary>
        public static string RegisterRemove {
            get {
                return ResourceManager.GetString("RegisterRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anwendung konnte nicht vom Autostart entfernt werden ähnelt.
        /// </summary>
        public static string RegisterRemoveFail {
            get {
                return ResourceManager.GetString("RegisterRemoveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neu laden ähnelt.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erinnerung ähnelt.
        /// </summary>
        public static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feierabend-Erinnerungsintervall (Minuten) ähnelt.
        /// </summary>
        public static string ReminderInterval {
            get {
                return ResourceManager.GetString("ReminderInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erinnerungsschwellwert (Stunden) ähnelt.
        /// </summary>
        public static string ReminderThreshold {
            get {
                return ResourceManager.GetString("ReminderThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte Anwendung beenden und neu starten!!!! ähnelt.
        /// </summary>
        public static string RestartApplication {
            get {
                return ResourceManager.GetString("RestartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speicherintervall (Minuten) ähnelt.
        /// </summary>
        public static string SaveInterval {
            get {
                return ResourceManager.GetString("SaveInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum auswählen ähnelt.
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein Datensatz ausgewählt ähnelt.
        /// </summary>
        public static string SelectRowFail {
            get {
                return ResourceManager.GetString("SelectRowFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lese Einstellungen ähnelt.
        /// </summary>
        public static string SettingsRead {
            get {
                return ResourceManager.GetString("SettingsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konnte Einstellungen nicht laden ähnelt.
        /// </summary>
        public static string SettingsReadFail {
            get {
                return ResourceManager.GetString("SettingsReadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen erfolgreich geladen ähnelt.
        /// </summary>
        public static string SettingsReadSuccess {
            get {
                return ResourceManager.GetString("SettingsReadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichere Einstellungen ähnelt.
        /// </summary>
        public static string SettingsSave {
            get {
                return ResourceManager.GetString("SettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konnte Einstellungen nicht speichern ähnelt.
        /// </summary>
        public static string SettingsSaveFail {
            get {
                return ResourceManager.GetString("SettingsSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen erfolgreich gespeichert ähnelt.
        /// </summary>
        public static string SettingsSaveSuccess {
            get {
                return ResourceManager.GetString("SettingsSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ton ähnelt.
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deaktiviere Ton ähnelt.
        /// </summary>
        public static string SoundDisable {
            get {
                return ResourceManager.GetString("SoundDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktiviere Ton ähnelt.
        /// </summary>
        public static string SoundEnable {
            get {
                return ResourceManager.GetString("SoundEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arbeitsbeginn ähnelt.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starte mit Windows ähnelt.
        /// </summary>
        public static string StartWithWindows {
            get {
                return ResourceManager.GetString("StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statistiken ähnelt.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum wählen ähnelt.
        /// </summary>
        public static string StatsDatePick {
            get {
                return ResourceManager.GetString("StatsDatePick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filtern ähnelt.
        /// </summary>
        public static string StatsFilterButton {
            get {
                return ResourceManager.GetString("StatsFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monat ähnelt.
        /// </summary>
        public static string StatsMonth {
            get {
                return ResourceManager.GetString("StatsMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Woche ähnelt.
        /// </summary>
        public static string StatsWeek {
            get {
                return ResourceManager.GetString("StatsWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jahr ähnelt.
        /// </summary>
        public static string StatsYear {
            get {
                return ResourceManager.GetString("StatsYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll dieser Tag wirklich gelöscht werden? ähnelt.
        /// </summary>
        public static string SureDelete {
            get {
                return ResourceManager.GetString("SureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tabelle ähnelt.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll ähnelt.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teste Warnton ähnelt.
        /// </summary>
        public static string TestSound {
            get {
                return ResourceManager.GetString("TestSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teste Toast ähnelt.
        /// </summary>
        public static string TestToast {
            get {
                return ResourceManager.GetString("TestToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bis ähnelt.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teste kritische Benachrichtigung ähnelt.
        /// </summary>
        public static string ToastTestCrit {
            get {
                return ResourceManager.GetString("ToastTestCrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teste warnende Benachrichtigung ähnelt.
        /// </summary>
        public static string ToastTestWarn {
            get {
                return ResourceManager.GetString("ToastTestWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brutto Arbeitszeit (inkl. Pausenzeit) ähnelt.
        /// </summary>
        public static string TooltipGross {
            get {
                return ResourceManager.GetString("TooltipGross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Netto Arbeitszeit (ohne Pausenzeit) ähnelt.
        /// </summary>
        public static string TooltipNet {
            get {
                return ResourceManager.GetString("TooltipNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll Arbeitszeit ähnelt.
        /// </summary>
        public static string TooltipTarget {
            get {
                return ResourceManager.GetString("TooltipTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arbeitszeit total (h) ähnelt.
        /// </summary>
        public static string TotalHoursWorked {
            get {
                return ResourceManager.GetString("TotalHoursWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konnte Zeit nicht in der Chronos Datenbank speichern ähnelt.
        /// </summary>
        public static string TTSaveFailed {
            get {
                return ResourceManager.GetString("TTSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konnte Darstellung in der Benutzeroberfläche nicht aktualisieren ähnelt.
        /// </summary>
        public static string UpdateVisualsFailed {
            get {
                return ResourceManager.GetString("UpdateVisualsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Letzte Woche ähnelt.
        /// </summary>
        public static string WeekLast {
            get {
                return ResourceManager.GetString("WeekLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diese Woche ähnelt.
        /// </summary>
        public static string WeekThis {
            get {
                return ResourceManager.GetString("WeekThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fensterverhalten ähnelt.
        /// </summary>
        public static string WindowBehavior {
            get {
                return ResourceManager.GetString("WindowBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fenster verbergen ähnelt.
        /// </summary>
        public static string WindowHide {
            get {
                return ResourceManager.GetString("WindowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fenster zeigen ähnelt.
        /// </summary>
        public static string WindowShow {
            get {
                return ResourceManager.GetString("WindowShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arbeitstage ähnelt.
        /// </summary>
        public static string WorkDays {
            get {
                return ResourceManager.GetString("WorkDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arbeitszeit ähnelt.
        /// </summary>
        public static string Worktime {
            get {
                return ResourceManager.GetString("Worktime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arbeitszeit hinzufügen: ähnelt.
        /// </summary>
        public static string WorktimeAdd {
            get {
                return ResourceManager.GetString("WorktimeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arbeitszeit löschen: ähnelt.
        /// </summary>
        public static string WorktimeDel {
            get {
                return ResourceManager.GetString("WorktimeDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arbeitszeit bearbeiten: ähnelt.
        /// </summary>
        public static string WorktimeEdit {
            get {
                return ResourceManager.GetString("WorktimeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arbeitszeitexport ähnelt.
        /// </summary>
        public static string WorktimeExport {
            get {
                return ResourceManager.GetString("WorktimeExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ansicht zurücksetzen ähnelt.
        /// </summary>
        public static string ZoomDefault {
            get {
                return ResourceManager.GetString("ZoomDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ansicht auf eine Seite anpassen ähnelt.
        /// </summary>
        public static string ZoomFitMaxPage {
            get {
                return ResourceManager.GetString("ZoomFitMaxPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ansicht auf zwei Seiten anpassen ähnelt.
        /// </summary>
        public static string ZoomFitTwoPages {
            get {
                return ResourceManager.GetString("ZoomFitTwoPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An Seitenbreite anpassen ähnelt.
        /// </summary>
        public static string ZoomFitWith {
            get {
                return ResourceManager.GetString("ZoomFitWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vergrößern ähnelt.
        /// </summary>
        public static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verkleinern ähnelt.
        /// </summary>
        public static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
